### ISSUE TITLE
Improvement: Support for syncfolder

### ISSUE THREAD

**Issue by aight8** [mlafeldt/chef-runner#62]
Instead of rsync all cookbooks, is it possible to use vagrant shared folder functionality?

**Comment by mlafeldt** [comment]
If you look into the early history of chef-runner -- back when it was just a shell script -- this was actually how things used to work. When I rewrote the tool in Go, I switched to using rsync+ssh because they works universally for all current drivers. (Also, shared folders won't work when specifying a machine's UUID with `-M`.)
